/**
 * Spanish overlay for Charts dashboard (loaded after dashboard-i18n.js).
 * Generated by scripts/gen-charts-es-overlay.mjs
 */
(function (global) {
  "use strict";
  var I18N = global.DashboardI18n;
  if (!I18N || !I18N.MSGS) return;
  var es = I18N.MSGS.es || (I18N.MSGS.es = {});
  var overlay = {
  "meta.title": "Indicadores económicos y sociales mundiales ({start}–{end})",
  "lang.toggleTitle": "Cambiar idioma",
  "lang.labelEn": "EN",
  "lang.labelFr": "FR",
  "lang.labelEs": "ES",
  "theme.toggleTitle": "Cambiar tema claro/oscuro",
  "theme.toggleAria": "Cambiar tema",
  "country.selectTitle": "Seleccionar países para comparar",
  "country.europeAggregateLabel": "Europa (agregado)",
  "overview.title": "Resumen de participación por país",
  "overview.metricNotePop": "Tamaño de baldosa ∝ participación poblacional (millones) entre los países mostrados.",
  "overview.metricNoteGdp": "Tamaño de baldosa ∝ participación del PIB (billones USD) entre los países mostrados.",
  "overview.metric.population": "Población",
  "overview.metric.gdp": "PIB",
  "overview.continent.all": "Todos",
  "overview.continent.africa": "África",
  "overview.continent.asia": "Asia",
  "overview.continent.europe": "Europa",
  "overview.continent.north_america": "Norteamérica",
  "overview.continent.south_america": "Sudamérica",
  "overview.continent.oceania": "Oceanía",
  "overview.mapToggle.africa": "África",
  "overview.mapToggle.asia": "Asia",
  "overview.mapToggle.europe": "Europa",
  "overview.mapToggle.north_america": "N. América",
  "overview.mapToggle.south_america": "S. América",
  "overview.mapToggle.oceania": "Oceanía",
  "overview.mapHint": "Haz clic en países del mapa o del treemap para alternar la selección. Los botones de continente activan o desactivan esos países.",
  "overview.emptyTreemap": "No hay países seleccionados en este continente.",
  "overview.treemapAria": "Treemap de participación por país",
  "overview.mapLoadFail": "No se pudo cargar el mapa mundial.",
  "tab.economic": "Economía",
  "tab.employment": "Empleo",
  "tab.costs": "Costos",
  "tab.social": "Social",
  "tab.demographics": "Población",
  "tab.health": "Salud",
  "tab.environment": "Medio ambiente",
  "tab.technology": "Tecnología",
  "tab.trade": "Comercio",
  "tab.immigration": "Migración",
  "tab.wellbeing": "Calidad de vida",
  "tab.governance": "Gobernanza",
  "tab.inequality": "Desigualdad",
  "tab.investment": "Inversión",
  "tab.energy": "Energía e industria",
  "tab.humanitarian": "Humanitario",
  "tab.labor": "Trabajo",
  "nav.group.macro": "Macro",
  "nav.group.people": "Personas",
  "nav.group.society": "Sociedad",
  "nav.group.planet": "Planeta",
  "nav.group.tech": "Tecnología",
  "nav.searchPlaceholder": "Buscar indicadores (p. ej. Gini, CO₂, Edelman, desempleo…)",
  "nav.searchAria": "Buscar indicadores del panel",
  "sec.statsSummary": "Resumen de indicadores clave",
  "sec.yoy": "Cambios interanuales ({prev} → {end})",
  "sec.comparison": "Comparación detallada de países ({end})",
  "sec.trends": "Tendencias de largo plazo ({start} → {end})",
  "sec.economic": "Indicadores económicos",
  "sec.military": "Gasto militar",
  "sec.employment": "Empleo e ingresos",
  "sec.costs": "Costo de vida",
  "sec.telecom": "Telecom y conectividad",
  "sec.social": "Indicadores sociales",
  "sec.demographics": "Indicadores demográficos",
  "sec.health": "Indicadores de salud",
  "sec.environment": "Indicadores ambientales",
  "sec.technology": "Adopción tecnológica",
  "sec.trade": "Comercio internacional",
  "sec.immigration": "Inmigración",
  "sec.wellbeing": "Calidad de vida y progreso social",
  "sec.governance": "Gobernanza y derechos",
  "sec.inequality": "Desigualdad y presión fiscal",
  "sec.investment": "Inversión y finanzas",
  "sec.energy": "Energía e industria",
  "sec.humanitarian": "Humanitario y asuntos globales",
  "sec.mediaTrust": "Confianza mediática (Edelman 2012+)",
  "sec.educationExt": "Educación (ampliado)",
  "sec.macroExt": "Macro y fiscal (ampliado, WDI)",
  "sec.demographicsExt": "Dinámica demográfica (WDI)",
  "sec.healthExt2": "Enfermedades y factores de riesgo (WDI)",
  "sec.environmentExt": "Medio ambiente y acceso (WDI)",
  "sec.techExt": "Producción de innovación (WDI)",
  "sec.labor": "Mercado laboral (WDI)",
  "sec.media": "Expresión y medios",
  "sec.religion": "Composición religiosa",
  "spec.chartHidden": "Gráfico oculto por datos insuficientes",
  "dq.title": "Instantánea de calidad de datos",
  "dq.summary": "Auditoría rápida de cobertura de fuentes y dependencia del modelo para el panel mostrado.",
  "dq.wdiLoaded": "Indicadores WDI cargados:",
  "dq.totalCharts": "Total de superficies de gráficos:",
  "dq.externalCharts": "Gráficos anclados a fuentes externas:",
  "dq.modelledCharts": "Gráficos aún basados en modelo:",
  "dq.horizon": "Horizonte temporal:",
  "dq.freshness": "Última actualización de datos en vivo:",
  "dq.warning": "Alerta de calidad:",
  "dq.warningLowCoverage": "Baja cobertura de fuentes en vivo; varios gráficos siguen basados en modelo.",
  "dq.warningOk": "Cobertura aceptable para uso básico del panel.",
  "dq.tabBreakdown": "Cobertura externa por pestaña:",
  "dq.countryCoverage": "Cobertura WDI de países seleccionados:",
  "dq.notAvailable": "n/d",
  "table.country": "País",
  "table.gdp": "PIB (T$)",
  "table.gdppc": "PIB/hab. ($)",
  "table.empl": "Empl. 15+ (%)",
  "table.gni": "RNB/hab. ($)",
  "table.life": "Esp. vida (años)",
  "table.rent": "Alquiler ($/mes)",
  "table.co2": "CO₂ (t/hab.)",
  "table.internet": "Internet (%)",
  "stats.range": "Rango:",
  "stats.avgGdp": "PIB medio (billones USD)",
  "stats.avgGdppc": "PIB per cápita medio (USD)",
  "stats.empl": "Empleo sobre población 15+ (%)",
  "stats.gni": "RNB per cápita medio (USD, WDI)",
  "stats.life": "Esperanza de vida media (años)",
  "stats.birth": "Tasa de natalidad media (por 1000)",
  "stats.rent": "Alquiler mensual medio (USD)",
  "stats.gas": "Precio medio del combustible (USD/L)",
  "stats.co2": "Emisiones medias de CO₂ (t/hab.)",
  "stats.edu": "Nivel educativo medio (%)",
  "stats.trade": "Balanza comercial media (miles de millones USD)",
  "stats.tradeB": "Balanza comercial media (miles de millones USD)",
  "stats.internet": "Penetración media de Internet (%)",
  "stats.cardGdpGrowth": "Crecimiento del PIB",
  "stats.cardEmpChange": "Cambio en la tasa de empleo",
  "stats.cardGniGrowth": "Crecimiento del RNB per cápita",
  "stats.cardCo2Change": "Cambio en emisiones de CO₂",
  "stats.cardAvgAcross": "Media de los países seleccionados",
  "stats.trendGdp": "Crecimiento total del PIB desde 1970",
  "stats.trendLife": "Ganancia de esperanza de vida desde 1970",
  "stats.trendLifeIncrease": "Aumento de la esperanza de vida",
  "stats.trendCo2": "Cambio de CO₂ desde 1970",
  "stats.trendAvg": "Media:",
  "stats.trendUnitYears": "años",
  "stats.trendUnitTons": "toneladas",
  "toast.minCountry": "Debe seleccionarse al menos un país",
  "wdi.ok": "Datos WDI del Banco Mundial fusionados correctamente.",
  "wdi.fail": "No se pudieron cargar los datos del Banco Mundial; los gráficos usan series modeladas.",
  "badge.highAccuracy": "Alta precisión",
  "badge.estimated": "Estimado",
  "badge.lowAccuracy": "Baja precisión",
  "badge.modelled": "Modelado",
  "badge.highWdi": "Alto (WDI)",
  "badge.partialWdi": "WDI parcial",
  "badge.mixedWdiPop": "Mixto (pob. WDI)",
  "badge.partialEdelman": "Parcial (Edelman)",
  "badge.yoy": "A/A",
  "badge.lowModelled": "Baja precisión — Modelado",
  "badge.lowWhr2012": "Baja precisión — datos WHR desde 2012",
  "badge.lowCpi1995": "Baja precisión — IPC solo desde 1995",
  "badge.lowPre1990": "Baja precisión — modelado antes de 1990",
  "note.giniInQol": "El gráfico del coeficiente de Gini está en la pestaña <strong>Calidad de vida</strong> — anclado a WDI cuando hay datos en vivo.",
  "note.mediaTrustGov": "<strong>Fuentes de confianza mediática:</strong> desde 2012, ancladas al Edelman Trust Barometer. Antes de 2012, modelados.",
  "note.mediaTrustSpeech": "Este bloque separa el entorno institucional de la expresión de la confianza en medios. Desde 2012, anclado al <strong>Edelman Trust Barometer</strong>.",
  "chart.axis.year": "Año",
  "spec.tag.logic": "Lógica",
  "spec.tag.better": "Si es cierto, mejor",
  "spec.tag.worse": "Si es cierto, peor",
  "spec.head": "Leer la tendencia (lógica)",
  "spec.note": "Trátelos como ayudas de interpretación, no como conclusiones.",
  "spec.fallbackCharts": "el/los gráfico(s) de arriba",
  "spec.guideNoChartTitles": "Use este panel con los indicadores de esta sección: empiece por la dirección de largo plazo, luego si las series se mueven juntas, y solo entonces infiera una historia.",
  "spec.accuracyPrefix": "Etiquetas de precisión aquí:",
  "spec.accuracyHint": "Confíe más en la dirección, el calendario y las brechas que en valores puntuales exactos.",
  "spec.readShape": "Lea primero la forma: tendencia, puntos de inflexión, y si las líneas se confirman o se contradicen.",
  "spec.panel.look": "Observe",
  "spec.panel.read": "Interprételo como",
  "spec.panel.caution": "No sobreinterprete",
  "spec.panel.lookText": "Rupturas compartidas, brechas que se amplían, o una línea que cambia de dirección mientras la otra se queda plana.",
  "spec.panel.readText": "Cuando varias series se mueven juntas, un factor común es plausible. Cuando divergen, pregunte qué cambió.",
  "spec.guideIntro": "Use este cuadro para interpretar",
  "spec.guideMid": ". Empiece por la dirección de largo plazo, compruebe si las líneas giran a la vez, y solo entonces infiera una historia.",
  "provenance.html": "<strong>Fuentes de datos:</strong> al cargar, la página solicita los <a href=\"https://data.worldbank.org/\" target=\"_blank\" rel=\"noopener\">Indicadores del desarrollo mundial</a> (WDI) del Banco Mundial y fusiona series clave. Los demás gráficos usan series modeladas deterministas."
};
  Object.keys(overlay).forEach(function (k) { es[k] = overlay[k]; });
  es["ct.gdpChart"] = "PIB (Billones USD)";
  es["ct.gdpPerCapitaChart"] = "PIB per cápita (USD)";
  es["ct.capitalGainsChart"] = "Average Capital Gains (USD)";
  es["ct.valuationChart"] = "Company Valuation Índice";
  es["ct.militaryBudgetChart"] = "Gasto militar (miles de millones USD)";
  es["ct.militaryShareChart"] = "Gasto militar (% of PIB)";
  es["ct.militaryPerCapitaChart"] = "Gasto militar per cápita (USD)";
  es["ct.productivityChart"] = "Productividad laboral Índice (1990 = 100)";
  es["ct.employmentChart"] = "Empleo sobre población (15+, %)";
  es["ct.unemploymentChart"] = "Tasa de desempleo (%)";
  es["ct.salaryChart"] = "RNB per cápita, Atlas (USD, WDI)";
  es["ct.foodCostChart"] = "Costos alimentarios (USD/month)";
  es["ct.rentChart"] = "Rent (USD/month)";
  es["ct.housingChart"] = "Costos de vivienda (USD)";
  es["ct.electricityChart"] = "Costos de electricidad (USD/month)";
  es["ct.gasChart"] = "Precio del combustible (USD/litre)";
  es["ct.carChart"] = "Car Costs (USD)";
  es["ct.phoneContractChart"] = "Monthly Phone Contract (USD/month)";
  es["ct.internetContractChart"] = "Monthly Broadband / Internet Contract (USD/month)";
  es["ct.tvContractChart"] = "Monthly TV / Streaming Subscription (USD/month)";
  es["ct.telecomBundleChart"] = "Total Telecom Bundle (Phone + Internet + TV) (USD/month)";
  es["ct.healthcareChart"] = "Health expenditure per cápita (WDI) (USD/year)";
  es["ct.foodbankChart"] = "Food Bank Costs (Million USD)";
  es["ct.homeownershipChart"] = "Tasa de propiedad de vivienda (%)";
  es["ct.ageChart"] = "Edad media (Años)";
  es["ct.educationChart"] = "Secondary school enrollment, gross (WDI) (%)";
  es["ct.literacyChart"] = "Tasa de alfabetización (%)";
  es["ct.deiChart"] = "DEI Índice (Puntuación 0-100)";
  es["ct.genderEqualityChart"] = "Gender Equality Índice (Índice 0-1)";
  es["ct.happinessChart"] = "Happiness Índice (Índice 0-10)";
  es["ct.politicalFreedomChart"] = "Libertad política Índice (Índice 0-10)";
  es["ct.violenceChart"] = "Violence Índice (Índice)";
  es["ct.birthRateChart"] = "Tasa de natalidad (Per 1000 people)";
  es["ct.deathRateChart"] = "Tasa de mortalidad (Per 1000 people)";
  es["ct.lifeExpectancyChart"] = "Esperanza de vida (Años)";
  es["ct.fertilityRateChart"] = "Tasa de fertilidad (Hijos por mujer)";
  es["ct.abortionRateChart"] = "Abortion Rate (Per 1,000 women ages 15-44)";
  es["ct.infantMortalityChart"] = "Mortalidad infantil Rate (Per 1000 nacidos vivos)";
  es["ct.obesityChart"] = "Tasa de obesidad (%)";
  es["ct.smokingChart"] = "Smoking Prevalence (%)";
  es["ct.diabetesChart"] = "Diabetes Rate (%)";
  es["ct.mentalHealthChart"] = "Mental Health Índice (Índice)";
  es["ct.co2EmissionsChart"] = "Emisiones de CO₂ (toneladas métricas per cápita)";
  es["ct.renewableEnergyChart"] = "Energía renovable (% de la energía total)";
  es["ct.forestCoverageChart"] = "Forest Coverage (% del territorio)";
  es["ct.waterQualityChart"] = "Water Quality Índice (Índice)";
  es["ct.internetUsersChart"] = "Usuarios de Internet (% de la población)";
  es["ct.mobilePhonesChart"] = "Mobile cellular subscriptions (per 100 people)";
  es["ct.broadbandSpeedChart"] = "Broadband Speed (Mbps)";
  es["ct.rndInvestmentChart"] = "R&D Investment (% of PIB)";
  es["ct.exportsChart"] = "Exportaciones (Miles de millones USD)";
  es["ct.importsChart"] = "Importaciones (Miles de millones USD)";
  es["ct.tradeBalanceChart"] = "Balanza comercial (Miles de millones USD)";
  es["ct.legalImmigrationChart"] = "Inmigración legal (Personas)";
  es["ct.illegalImmigrationChart"] = "Inmigración irregular (Personas)";
  es["ct.legalImmigrationPerCapitaChart"] = "Inmigración legal per cápita (Per 100k people)";
  es["ct.illegalImmigrationPerCapitaChart"] = "Inmigración irregular per cápita (Per 100k people)";
  es["ct.immigrationNativeRatioChart"] = "Immigration Inflow Ratio (% of resident population)";
  es["ct.expatArrivalsChart"] = "Expat Arrivals (Personas)";
  es["ct.expatDeparturesChart"] = "Expat Departures (Personas)";
  es["ct.qolIndexChart"] = "Índice de calidad de vida (Puntuación 0–100)";
  es["ct.qolHappinessChart"] = "Happiness Índice (World Happiness Report basis) (Puntuación 0–10)";
  es["ct.hdiChart"] = "Índice de desarrollo humano (HDI 0–1)";
  es["ct.giniChart"] = "Coeficiente de Gini – Income Inequality (Gini 0 = equal, 100 = unequal)";
  es["ct.corruptionChart"] = "Índice de percepción de la corrupción (Puntuación 0–100, higher = cleaner)";
  es["ct.qolPoliticalChart"] = "Libertad política Índice (Puntuación 0–10)";
  es["ct.freeSpeechChart"] = "Libertad de expresión Rating (Puntuación 0–10)";
  es["ct.legacyMediaRatingChart"] = "Legacy Media Trust Rating (Puntuación 0–10, Edelman 2012+)";
  es["ct.newMediaRatingChart"] = "New Media Trust Rating (Puntuación 0–10, Edelman 2012+)";
  es["ct.legacyMediaShareChart"] = "Legacy Media Market Cuota (Cuota %)";
  es["ct.newMediaShareChart"] = "New Media Market Cuota (Cuota %)";
  es["ct.ruleOfLawChart"] = "Rule of Law Índice (WGI, −2.5 to +2.5)";
  es["ct.govEffectivenessChart"] = "Government Effectiveness (WGI)";
  es["ct.regulatoryQualityChart"] = "Regulatory Quality (WGI)";
  es["ct.voiceAccountabilityChart"] = "Voice & Accountability (WGI)";
  es["ct.womenParliamentChart"] = "Women in Parliament (%)";
  es["ct.govLegacyMediaTrustChart"] = "Legacy / Traditional Media Trust (Edelman, 0–10)";
  es["ct.govNewMediaTrustChart"] = "New / Digital Media Trust (Edelman, 0–10)";
  es["ct.povertyHeadcountChart"] = "Tasa de pobreza ($2.15/day, %)";
  es["ct.inflationChart"] = "Inflation, CPI (annual %)";
  es["ct.publicDebtChart"] = "Deuda pública (% of PIB)";
  es["ct.fdiInflowsChart"] = "FDI Inflows (% of PIB)";
  es["ct.fdiOutflowsChart"] = "FDI Outflows (% of PIB)";
  es["ct.capitalFormationChart"] = "Gross Capital Formation (% of PIB)";
  es["ct.remittancesChart"] = "Remittances Received (% of PIB)";
  es["ct.marketCapChart"] = "Stock Market Cap (% of PIB)";
  es["ct.co2TotalChart"] = "Emisiones totales de CO₂ (kt)";
  es["ct.energyUseChart"] = "Energy Use (kg oil eq. per cápita)";
  es["ct.fossilFuelChart"] = "Fossil Fuel Cuota (% of energy)";
  es["ct.elecRenewableChart"] = "Electricity from Renewables (%)";
  es["ct.pm25Chart"] = "PM2.5 Air Pollution (μg/m³)";
  es["ct.industryGdpChart"] = "Industry Value Added (% of PIB)";
  es["ct.manufacturingGdpChart"] = "Manufacturing (% of PIB)";
  es["ct.hiTechExportsChart"] = "High-Tech Exportaciones (% of mfg exports)";
  es["ct.protectedAreasChart"] = "Protected Areas (% of land)";
  es["ct.odaReceivedChart"] = "ODA Received (% of GNI)";
  es["ct.netMigrationChart"] = "Net Migration (people)";
  es["ct.militaryPersonnelChart"] = "Armed Forces (% of labor force)";
  es["ct.eduPrimaryChart"] = "Primary Enrollment (% gross)";
  es["ct.eduTertiaryChart"] = "Tertiary Enrollment (% gross)";
  es["ct.eduSpendingChart"] = "Gasto en educación (% of PIB)";
  es["ct.under5MortalityChart"] = "Under-5 Mortality (per 1,000 nacidos vivos)";
  es["ct.maternalMortalityChart"] = "Maternal Mortality Ratio (per 100,000 nacidos vivos)";
  es["ct.gdpGrowthChart"] = "Crecimiento del PIB (annual %)";
  es["ct.currentAccountChart"] = "Current Account Balance (% of PIB)";
  es["ct.taxRevenueChart"] = "Ingresos fiscales (% of PIB)";
  es["ct.tradeGdpChart"] = "Trade (% of PIB)";
  es["ct.incomeBottom20Chart"] = "Income Cuota – Bottom 20% (%)";
  es["ct.incomeTop10Chart"] = "Income Cuota – Top 10% (%)";
  es["ct.poverty365Chart"] = "Tasa de pobreza ($3.65/day, %)";
  es["ct.controlCorruptionChart"] = "Control of Corruption (WGI, −2.5 to +2.5)";
  es["ct.politicalStabilityChart"] = "Political Stability (WGI, −2.5 to +2.5)";
  es["ct.hivPrevalenceChart"] = "HIV Prevalence (% ages 15–49)";
  es["ct.tuberculosisChart"] = "Tuberculosis Incidence (per 100,000)";
  es["ct.suicideRateChart"] = "Suicide Mortality Rate (per 100,000)";
  es["ct.alcoholConsumptionChart"] = "Alcohol Consumption (litres pure alcohol/capita)";
  es["ct.co2IntensityChart"] = "CO₂ Intensity (kg per PPP $ of PIB)";
  es["ct.arableLandChart"] = "Arable Land (% del territorio)";
  es["ct.freshwaterWithdrawalChart"] = "Freshwater Withdrawal (billion m³)";
  es["ct.electricityAccessChart"] = "Access to Electricity (% de la población)";
  es["ct.cleanFuelAccessChart"] = "Access to Clean Fuels for Cooking (%)";
  es["ct.populationGrowthChart"] = "Crecimiento demográfico (annual %)";
  es["ct.urbanPopulationChart"] = "Población urbana (% of total)";
  es["ct.ageDependencyChart"] = "Age Dependency Ratio (% of working-age population)";
  es["ct.schoolLifeExpectancyChart"] = "School Esperanza de vida (years)";
  es["ct.domesticCreditChart"] = "Domestic Credit to Private Sector (% of PIB)";
  es["ct.youthUnemploymentChart"] = "Desempleo juvenil (% ages 15–24)";
  es["ct.vulnerableEmploymentChart"] = "Vulnerable Employment (% of total employment)";
  es["ct.femaleLaborForceChart"] = "Female Labor Force Participation (% ages 15+)";
  es["ct.maleLaborForceChart"] = "Male Labor Force Participation (% ages 15+)";
  es["ct.researchersChart"] = "Researchers in R&D (per million people)";
  es["ct.patentsChart"] = "Patent Applications (residents)";
  es["ct.serviceExportsChart"] = "Service Exportaciones (billion USD)";
  es["ct.militarySpendWdiChart"] = "Gasto militar (% of PIB, WDI)";
  es["ct.populationTotalChart"] = "Población total (millions, WDI)";
  es["ct.healthSpendGdpChart"] = "Gasto en salud (% of PIB, WDI)";
  es["ct.surgeryWaitChart"] = "Median Elective Surgery Wait Time (Semanas)";
  es["ct.physiciansChart"] = "Physicians per 1,000 Personas (Physicians / 1k)";
  es["ct.hospitalBedsChart"] = "Hospital Beds per 1,000 Personas (Beds / 1k)";
  es["ct.qolHealthcareChart"] = "Healthcare Expenditure per Capita (USD / year)";
  es["ct.christianChart"] = "Christian Population Cuota (%)";
  es["ct.muslimChart"] = "Muslim Population Cuota (%)";
  es["ct.secularChart"] = "Secular / Unaffiliated Population Cuota (%)";
  es["ct.hinduBuddhistChart"] = "Hindu & Buddhist Population Cuota (%)";
  es["cy.gdpChart"] = "Billones USD";
  es["cy.gdpPerCapitaChart"] = "USD";
  es["cy.capitalGainsChart"] = "USD";
  es["cy.valuationChart"] = "Índice";
  es["cy.militaryBudgetChart"] = "miles de millones USD";
  es["cy.militaryShareChart"] = "% of PIB";
  es["cy.militaryPerCapitaChart"] = "USD/person";
  es["cy.productivityChart"] = "Índice (1990 = 100)";
  es["cy.employmentChart"] = "%";
  es["cy.unemploymentChart"] = "%";
  es["cy.salaryChart"] = "USD";
  es["cy.foodCostChart"] = "USD/month";
  es["cy.rentChart"] = "USD/month";
  es["cy.housingChart"] = "USD";
  es["cy.electricityChart"] = "USD/month";
  es["cy.gasChart"] = "USD/litre";
  es["cy.carChart"] = "USD";
  es["cy.phoneContractChart"] = "USD/month";
  es["cy.internetContractChart"] = "USD/month";
  es["cy.tvContractChart"] = "USD/month";
  es["cy.telecomBundleChart"] = "USD/month";
  es["cy.healthcareChart"] = "USD/year";
  es["cy.foodbankChart"] = "Million USD";
  es["cy.homeownershipChart"] = "%";
  es["cy.ageChart"] = "Años";
  es["cy.educationChart"] = "%";
  es["cy.literacyChart"] = "%";
  es["cy.deiChart"] = "Puntuación (0-100)";
  es["cy.genderEqualityChart"] = "Índice (0-1)";
  es["cy.happinessChart"] = "Índice (0-10)";
  es["cy.politicalFreedomChart"] = "Índice (0-10)";
  es["cy.violenceChart"] = "Índice";
  es["cy.birthRateChart"] = "Per 1000 people";
  es["cy.deathRateChart"] = "Per 1000 people";
  es["cy.lifeExpectancyChart"] = "Años";
  es["cy.fertilityRateChart"] = "Hijos por mujer";
  es["cy.abortionRateChart"] = "Per 1,000 women ages 15-44";
  es["cy.infantMortalityChart"] = "Per 1000 nacidos vivos";
  es["cy.obesityChart"] = "%";
  es["cy.smokingChart"] = "%";
  es["cy.diabetesChart"] = "%";
  es["cy.mentalHealthChart"] = "Índice";
  es["cy.co2EmissionsChart"] = "toneladas métricas per cápita";
  es["cy.renewableEnergyChart"] = "% de la energía total";
  es["cy.forestCoverageChart"] = "% del territorio";
  es["cy.waterQualityChart"] = "Índice";
  es["cy.internetUsersChart"] = "% de la población";
  es["cy.mobilePhonesChart"] = "per 100 people";
  es["cy.broadbandSpeedChart"] = "Mbps";
  es["cy.rndInvestmentChart"] = "% of PIB";
  es["cy.exportsChart"] = "Miles de millones USD";
  es["cy.importsChart"] = "Miles de millones USD";
  es["cy.tradeBalanceChart"] = "Miles de millones USD";
  es["cy.legalImmigrationChart"] = "Personas";
  es["cy.illegalImmigrationChart"] = "Personas";
  es["cy.legalImmigrationPerCapitaChart"] = "Per 100k people";
  es["cy.illegalImmigrationPerCapitaChart"] = "Per 100k people";
  es["cy.immigrationNativeRatioChart"] = "% of resident population";
  es["cy.expatArrivalsChart"] = "Personas";
  es["cy.expatDeparturesChart"] = "Personas";
  es["cy.qolIndexChart"] = "Puntuación (0–100)";
  es["cy.qolHappinessChart"] = "Puntuación (0–10)";
  es["cy.hdiChart"] = "HDI (0–1)";
  es["cy.giniChart"] = "Gini (0 = equal, 100 = unequal)";
  es["cy.corruptionChart"] = "Puntuación (0–100, higher = cleaner)";
  es["cy.qolPoliticalChart"] = "Puntuación (0–10)";
  es["cy.freeSpeechChart"] = "Puntuación (0–10)";
  es["cy.legacyMediaRatingChart"] = "Puntuación (0–10)";
  es["cy.newMediaRatingChart"] = "Puntuación (0–10)";
  es["cy.legacyMediaShareChart"] = "Cuota (%)";
  es["cy.newMediaShareChart"] = "Cuota (%)";
  es["cy.surgeryWaitChart"] = "Semanas";
  es["cy.physiciansChart"] = "Physicians / 1k";
  es["cy.hospitalBedsChart"] = "Beds / 1k";
  es["cy.qolHealthcareChart"] = "USD / an";
  es["cy.christianChart"] = "% de la población";
  es["cy.muslimChart"] = "% de la población";
  es["cy.secularChart"] = "% de la población";
  es["cy.hinduBuddhistChart"] = "% de la población";
  es["cy.ruleOfLawChart"] = "WGI index";
  es["cy.govEffectivenessChart"] = "WGI index";
  es["cy.regulatoryQualityChart"] = "WGI index";
  es["cy.voiceAccountabilityChart"] = "WGI index";
  es["cy.womenParliamentChart"] = "%";
  es["cy.govLegacyMediaTrustChart"] = "Puntuación (0–10)";
  es["cy.govNewMediaTrustChart"] = "Puntuación (0–10)";
  es["cy.povertyHeadcountChart"] = "%";
  es["cy.inflationChart"] = "% anual";
  es["cy.publicDebtChart"] = "% of PIB";
  es["cy.fdiInflowsChart"] = "% of PIB";
  es["cy.fdiOutflowsChart"] = "% of PIB";
  es["cy.capitalFormationChart"] = "% of PIB";
  es["cy.remittancesChart"] = "% of PIB";
  es["cy.marketCapChart"] = "% of PIB";
  es["cy.co2TotalChart"] = "kt";
  es["cy.energyUseChart"] = "kg oil eq./capita";
  es["cy.fossilFuelChart"] = "% of energy";
  es["cy.elecRenewableChart"] = "%";
  es["cy.pm25Chart"] = "μg/m³";
  es["cy.industryGdpChart"] = "% of PIB";
  es["cy.manufacturingGdpChart"] = "% of PIB";
  es["cy.hiTechExportsChart"] = "% of mfg exports";
  es["cy.protectedAreasChart"] = "% of land";
  es["cy.odaReceivedChart"] = "% of GNI";
  es["cy.netMigrationChart"] = "Personas";
  es["cy.militaryPersonnelChart"] = "% of labor force";
  es["cy.eduPrimaryChart"] = "% gross";
  es["cy.eduTertiaryChart"] = "% gross";
  es["cy.eduSpendingChart"] = "% of PIB";
  es["cy.under5MortalityChart"] = "Per 1,000 nacidos vivos";
  es["cy.maternalMortalityChart"] = "Per 100,000 nacidos vivos";
  es["cy.gdpGrowthChart"] = "% anual";
  es["cy.currentAccountChart"] = "% of PIB";
  es["cy.taxRevenueChart"] = "% of PIB";
  es["cy.tradeGdpChart"] = "% of PIB";
  es["cy.incomeBottom20Chart"] = "%";
  es["cy.incomeTop10Chart"] = "%";
  es["cy.poverty365Chart"] = "%";
  es["cy.controlCorruptionChart"] = "WGI index";
  es["cy.politicalStabilityChart"] = "WGI index";
  es["cy.hivPrevalenceChart"] = "%";
  es["cy.tuberculosisChart"] = "Per 100,000";
  es["cy.suicideRateChart"] = "Per 100,000";
  es["cy.alcoholConsumptionChart"] = "Litres/capita";
  es["cy.co2IntensityChart"] = "kg/PPP $";
  es["cy.arableLandChart"] = "% of land";
  es["cy.freshwaterWithdrawalChart"] = "Billion m³";
  es["cy.electricityAccessChart"] = "%";
  es["cy.cleanFuelAccessChart"] = "%";
  es["cy.populationGrowthChart"] = "% anual";
  es["cy.urbanPopulationChart"] = "%";
  es["cy.ageDependencyChart"] = "%";
  es["cy.schoolLifeExpectancyChart"] = "Años";
  es["cy.domesticCreditChart"] = "% of PIB";
  es["cy.youthUnemploymentChart"] = "%";
  es["cy.vulnerableEmploymentChart"] = "%";
  es["cy.femaleLaborForceChart"] = "%";
  es["cy.maleLaborForceChart"] = "%";
  es["cy.researchersChart"] = "Per million";
  es["cy.patentsChart"] = "Applications";
  es["cy.serviceExportsChart"] = "Miles de millones USD";
  es["cy.militarySpendWdiChart"] = "% of PIB";
  es["cy.populationTotalChart"] = "Millions";
  es["cy.healthSpendGdpChart"] = "% of PIB";
})(typeof window !== "undefined" ? window : this);
